# Migrate issues from redmine to github
# follow general approach in
# https://blogs.harvard.edu/rprasad/2014/07/10/moving-from-redmine-to-github-issues/
# but using different tools

# install packages ----
# devtools::install_github("openanalytics/redmineR")
# devtools::install_github("r-lib/gh")
library(redmineR)
library(gh)

# References ----
# Documentation for github's v.3 REST API:
# https://developer.github.com/v3/issues/

# Plan A: use readmineR to read, gh to create new issues ----

# set system environment ----
# can also do this in a .Renviron file, I think?
Sys.setenv("REDMINE_URL" = "https://vlab.ncep.noaa.gov/redmine/")
# replace CHANGEME with your tokens
# redmine token (API access key) available at LHS of
# https://vlab.ncep.noaa.gov/redmine/my/account
Sys.setenv("REDMINE_TOKEN" = "CHANGEME") 
# github token can be generated by following these instructions:
# https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token#creating-a-token
Sys.setenv("GITHUB_TOKEN" = "CHANGEME")


# Get the issues from redmine. Save as R object. ----
# Use https://github.com/openanalytics/redmineR to get them.
#all_projects <- redmine_projects()

# download a single issue. Probably the easiest thing to do would be to 
# get a list of the issue ids we want to migrate over, then call this command
# iteratively, creating a list of the issues.
saved_issue <- redmine_show_issue(issue_id = 83862, include = "all")

#TODO save json, use RJSONIO????

# Manipulate them as needed for github.
# some manually written code, following suggestions in 
# https://blogs.harvard.edu/rprasad/2014/07/10/moving-from-redmine-to-github-issues/

#create the new issues on github ----
# use https://github.com/r-lib/gh
#  need to use with the github REST API v 3 documentation
# https://docs.github.com/en/free-pro-team@latest/rest


# create a generic issue, using hard coded values
gh("POST /repos/{owner}/{repo}/issues",
   owner = "nmfs-stock-synthesis", 
   repo = "test-issue-migration", 
   title = "test title, with description + assignee + label",
   body = "Here is some text\n not sure if line breaks work.",
   assignees = I("k-doering-NOAA"), 
   labels = I("label me")
   )

# create a new issue, using some information from the saved issue

gh("POST /repos/{owner}/{repo}/issues",
   owner = "nmfs-stock-synthesis", 
   repo = "test-issue-migration", 
   title = saved_issue$content$issue$subject,
   body = paste0("Imported from redmine, Issue #", 
   saved_issue$content$issue$id, "\n Opened by ", 
   saved_issue$content$issue$author$name, ".\n", 
   saved_issue$content$issue$description),
   labels = I(paste0("Priority: ", saved_issue$content$issue$priority$name))
)

# Add a note to the just created issue, hard coding the issue number for now
gh("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", 
   owner = "nmfs-stock-synthesis", 
   repo = "test-issue-migration", 
   issue_number = 1, 
   body = paste0("comment from ", saved_issue$content$issue$journals[[1]]$user$name, 
                 ":\n", saved_issue$content$issue$journals[[1]]$notes)
)

# Plan B: use .csv files ----
# create bulk issues from a .csv file. Will loose more information
# https://medium.com/@scott.j.jackson/how-to-bulk-create-issues-in-github-a278d429b7bf