# Migrate issues from redmine to github
# use readmineR to read, gh to create new issues
# follow general approach in
# https://blogs.harvard.edu/rprasad/2014/07/10/moving-from-redmine-to-github-issues/
# but using different tools

# install packages ----
# devtools::install_github("openanalytics/redmineR")
# devtools::install_github("r-lib/gh")
library(redmineR)
library(gh)

# set system environment ----
# can also do this in a .Renviron file
# Sys.setenv("REDMINE_URL" = "https://vlab.ncep.noaa.gov/redmine/")
# # replace CHANGEME with your tokens
# # redmine token (API access key) available at LHS of
# # https://vlab.ncep.noaa.gov/redmine/my/account
# Sys.setenv("REDMINE_TOKEN" = "CHANGEME") 
# # github token can be generated by following these instructions:
# # https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token#creating-a-token
# Sys.setenv("GITHUB_TOKEN" = "CHANGEME")


# Get the issues from redmine. Save as R object. ----
# Use https://github.com/openanalytics/redmineR to get them.
#all_projects <- redmine_projects()

# download a single issue. Probably the easiest thing to do would be to 
# get a list of the issue ids we want to migrate over, then call this command
# iteratively, creating a list of the issues.
issue_vec <- c(83862, 83773, 83123, 83053, 82969)

# Read in a .csv containing all tagged issues, with their associated tags.
issue_tag_key <- read.csv("issues_tags_key.csv")
colnames(issue_tag_key) <- c("id", "tags")

#' Get info for a redmine issue
#'
#' @param issue_number The redmine issue number
#' @param issue_tag_key Dataframe of issues and their associated tags. Need this
#'  because it doesn't seem possible to get info on tags from the API
get_redmine_issue <- function(issue_number, issue_tag_key) {
  tmp_tags <- issue_tag_key[issue_tag_key$id == issue_number,"tags"]
  if(length(grep(",", tmp_tags) > 0)) {
    tmp_tags <- strsplit(tmp_tags, ", ")[[1]]
  }
  issue_info <- 
    redmineR::redmine_show_issue(issue_id = issue_number, include = "all")
  Sys.sleep(1) # wait 1 second, to avoid overtaxing the API
  # TODO add code to read issue
  issue_info$content$issue$tags <- tmp_tags
  issue_info
}

all_issue_list <- lapply(issue_vec, 
                    function(num, key) {
                      tryCatch(get_redmine_issue(issue_number = num, 
                                                 issue_tag_key = key),
                               error = function(e) e)
                      }, 
                    key = issue_tag_key)
names(all_issue_list) <- issue_vec


#create the new issues on github ----

# some manually written code, following suggestions in 
# https://blogs.harvard.edu/rprasad/2014/07/10/moving-from-redmine-to-github-issues/
# use https://github.com/r-lib/gh
#  need to use with the github REST API v 3 documentation
# https://docs.github.com/en/free-pro-team@latest/rest

user_key <- c("chantelwetzel-noaa", "iantaylor-NOAA", "k-doering-NOAA",
              "kellijohnson-NOAA", "RickMethot")
names(user_key) <- c("chantel.wetzel", "ian.taylor", "kathryn.doering", 
                     "kelli.johnson", "richard.methot")


#' Create an issue on github using info from redmine
#' 
#' @param redmine_issue_info Information from 1 redmine issue
#' @param user_key A vector of github usernames, where the names of each 
#'  component are the corresponding redmine names
create_issue <- function(redmine_issue_info, user_key) {
  
  match_user_key <- function(redmine_val, user_key) {
    if(length(redmine_val) == 0) {
      return(list())
    }
    tmp_val <- user_key[which(names(user_key) == redmine_val)]
    if(length(tmp_val) == 0) {
      tmp_val <- redmine_val
    } else if(length(tmp_val) > 1) {
      warning("Issue with setting the name: found multiple")
      tmp_val <- redmine_val
    } else {
      tmp_val <- paste0("@", tmp_val)
    }
    tmp_val
  }
  
  tmp_assignee <- match_user_key(redmine_issue_info$content$issue$assignee$name, 
                                 user_key)
  tmp_author <- match_user_key(redmine_issue_info$content$issue$author$name, 
                               user_key)
  # add priority, category, and tags as labels.
  tmp_labels <- redmine_issue_info$content$issue$tags
  if(!is.null(redmine_issue_info$content$issue$priority$name)) {
      tmp_labels <- c(tmp_labels, 
        paste0("Priority: ", redmine_issue_info$content$issue$priority$name))
  }
  if(!is.null(redmine_issue_info$content$issue$category$name)) {
      tmp_labels <- c(tmp_labels,
        paste0("Category: ", redmine_issue_info$content$issue$category$name))
  }
  if(length(tmp_labels) == 0) {
    tmp_labels <- list()
  }
  tmp_info <- gh::gh("POST /repos/{owner}/{repo}/issues",
     owner = "nmfs-stock-synthesis", 
     repo = "test-issue-migration", 
     title = redmine_issue_info$content$issue$subject,
     body = paste0("Imported from redmine, Issue [#", 
                   redmine_issue_info$content$issue$id, 
                   "](https://vlab.ncep.noaa.gov/redmine/issues/",
                   redmine_issue_info$content$issue$id, ")\n Opened by ", 
                   tmp_author, " on ",
                   redmine_issue_info$content$issue$start_date, "\n",
                   "Status when imported: ", 
                   redmine_issue_info$content$issue$status$name, "\n \n",
                   redmine_issue_info$content$issue$description),
     labels = I(tmp_labels), 
     assignees = I(tmp_assignee))
  Sys.sleep(1)
  # Add notes, if any
  if(!is.null(redmine_issue_info$content$issue[["journals"]])) {
    tmp_cmts <- redmine_issue_info$content$issue[["journals"]]
    all_cmt_info <- lapply(tmp_cmts, function(x, user_key) {
      # get the github user name, if available
      tmp_user <- user_key[which(names(user_key) == x$user$name)]
      if(length(tmp_user) == 0) {
        tmp_user <- x$user$name
      } else if(length(tmp_user) > 1) {
        stop("Issue with setting the user name for comment: found multiple")
      } else {
        tmp_user <- paste0("@", tmp_user)
      }
      # Add a note to the just created issue, hard coding the issue number for now
      cmt_info <- gh::gh("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", 
         owner = "nmfs-stock-synthesis", 
         repo = "test-issue-migration", 
         issue_number = tmp_info$number, 
         body = paste0("comment from ", tmp_user,
                       ":\n", x$notes)
      )
      Sys.sleep(1)
      cmt_info
    }, user_key = user_key)
  }
  tmp_info # could also make another API call to get all issue info, if desired?
}

created_issue_info <- lapply(all_issue_list, 
                        function(x, user_key) {
                          tryCatch(create_issue(x, user_key),
                                   error = function(e) e)
                        },
                        user_key = user_key)
# save the migrated issue data
saveRDS(all_issue_list, "all_issue_list.rds")
saveRDS(created_issue_info, "created_issue_info.rds")